// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAfJfqqkmUBGzvyF6QK0PeQTDvuBaEWEY',
    appId: '1:142832891113:web:2b7f487d7f676eee3d2c78',
    messagingSenderId: '142832891113',
    projectId: 'fir-flutter-codelab-ac4d1',
    authDomain: 'fir-flutter-codelab-ac4d1.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-ac4d1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjPtc70HahmAYvjjqthAI0wWDfF3CG86c',
    appId: '1:142832891113:android:c76b7b08af781f383d2c78',
    messagingSenderId: '142832891113',
    projectId: 'fir-flutter-codelab-ac4d1',
    storageBucket: 'fir-flutter-codelab-ac4d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByrWLHGGt2pTDfZr6YOOQFVllu91VKHM0',
    appId: '1:142832891113:ios:40780a684e27a0823d2c78',
    messagingSenderId: '142832891113',
    projectId: 'fir-flutter-codelab-ac4d1',
    storageBucket: 'fir-flutter-codelab-ac4d1.appspot.com',
    iosClientId: '142832891113-kett6a0o0nk20vtnu9q7dpgos3orq1i1.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByrWLHGGt2pTDfZr6YOOQFVllu91VKHM0',
    appId: '1:142832891113:ios:40780a684e27a0823d2c78',
    messagingSenderId: '142832891113',
    projectId: 'fir-flutter-codelab-ac4d1',
    storageBucket: 'fir-flutter-codelab-ac4d1.appspot.com',
    iosClientId: '142832891113-kett6a0o0nk20vtnu9q7dpgos3orq1i1.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
